### PR TITLE
Add Spinup to cosmo-ghg test case

### PR DESCRIPTION
**Pull request by mjaehn**

### CODE REVIEW

**Comment by mjaehn** [comment]
launch jenkins

**Comment by mjaehn** [comment]
launch jenkins

**Comment by mjaehn** [comment]
The branch was already existing for a longer time. I want to merge it in preparation for the upcoming changes ([Updating and consolidating Processing Chain for ICON-ART](https://wiki.c2sm.ethz.ch/pub/ORGANIZATION/ORGTasksWG22023/Task_2023-1_WG2_Processing_Chain_2023.pdf))

**Review by efmkoene — COMMENTED** [review]
I have a few comments to make it more easy to use it all (better make these changes now before we continue making harder cases further on?; if you think the changes are out of scope here then please make a few issues based on the following to close later).

1. The instructions don't contain an instruction to install `int2lm`. This should be added, I think?
2. For the cosmoghg 11km testcase I have a number of issues related to running this with CPU (`mc`) instead of GPU (`gpu`):
    1. The number of nodes goes to zero due to `cosmo_np_tot = int(cosmo_np_x * cosmo_np_y / ntasks_per_node) + cosmo_np_io` = `int( 4 * 3 / 36) + 0=0`.
    2. We need to change `cosmo_bin` to use `/bin/cosmo-ghg_cpu`
    4. In `cosmo_INPUT_DYN.cfg` we need `lcpp_dycore=.FALSE.` instead of `lcpp_dycore=.TRUE.`
    3. In `cosmo_spec` we need `cosmo@empa-ghg%nvhpc cosmo_target=cpu ~cppdycore`

Other than that, the (new) testcase appears to work. Let me know how you plan to approach these comments, I'll happily approve the change in and by itself otherwise.

**Comment by mjaehn** [comment]
Hi @efmkoene, this PR should only focus on the spinup. I agree that your suggestions rather fit to the issues category. The testcase itself is only executed for the gpu version of cosmo-ghg. It is also not possible to do automated testing on `mc` nodes.

Conceptually, a number of changes will follow:

- use the new spack v0.18.1 https://github.com/C2SM/processing-chain/pull/15
- integration of new icon-art cases
- overhaul of the whole processing chain, e.g. config files will become `config.yaml` and the `run_chain.py` won't have any specific model information anymore

**Review by efmkoene — APPROVED** [review]
OK, then it is good to go 👍

**Pull request merged**
