### PR TITLE
Add Euler support and update to Python 3.11

### PR DESCRIPTION
**Pull request by mjaehn**
# Basic Euler Support
- Add `icon-euler-test` case
- Set machine (`daint` or `euler`) based on `hostname`
- Use different `SBATCH` commands for Euler

# Adapt Build Scripts
- Just build (and don't install) packages
- `dev-build` for icontools
- Reorganize stages in `Jenkinsfile`
- Add `common.sh` for build script functions

# Misc
- Update to Python version 3.11
- Remove `pillow` and add `pyyaml` to `requirements.txt`
- Small fixes

### CODE REVIEW

**Comment by mjaehn** [comment]
launch jenkins

**Comment by mjaehn** [comment]
launch jenkins

**Comment by mjaehn** [comment]
launch jenkins

**Comment by mjaehn** [comment]
launch jenkins

**Comment by mjaehn** [comment]
launch jenkins

**Comment by mjaehn** [comment]
launch jenkins

**Comment by mjaehn** [comment]
launch jenkins

**Comment by mjaehn** [comment]
launch jenkins

**Comment by mjaehn** [comment]
launch jenkins

**Comment by mjaehn** [comment]
launch jenkins

**Comment by mjaehn** [comment]
launch jenkins

**Comment by mjaehn** [comment]
launch jenkins

**Comment by mjaehn** [comment]
launch jenkins

**Review by leclairm — APPROVED** [review]
I happily blindly approve this PR :-)

**Pull request merged**
