### PR TITLE
Increase the temporal resolution of COSMO output

### PR DESCRIPTION
**Pull request by efmkoene**
This commit was introduced by Stephan. The new attribute 'inidate_yyyymmddhhmmss' will cause COSMO to generate date/time stamps for the output that include minutes and seconds [e.g., with filename lffdYYYYMMDDHHMMSS = lffd20180719184500]. This allows us to generate COSMO outputs at a 15-minute resolution with the corresponding filenames.

### CODE REVIEW

**Comment by mjaehn** [comment]
The other PR is merged. You may now merge `master` into `increased_temporal_resolution` and push again.

**Comment by efmkoene** [comment]
Okay, it should be good now. Thanks for the heads up!

**Comment by mjaehn** [comment]
launch jenkins

**Comment by mjaehn** [comment]
launch jenkins

**Comment by mjaehn** [comment]
Looking good to me!

**Comment by efmkoene** [comment]
If you review it, you can merge :-)

**Review by mjaehn — APPROVED** [review]

**Pull request merged**
