### PR TITLE
v3.0

### PR DESCRIPTION
**Pull request by mjaehn**
# Processing Chain v3.0

This PR includes all recent work on refactoring the code, as well as integration global ICON-ART simulations.

### CODE REVIEW

**Comment by mjaehn** [comment]
launch jenkins

**Comment by mjaehn** [comment]
Jenkins Test for this one: https://jenkins-mch.cscs.ch/job/ProcessingChain/job/processing-chain-PR/62/

**Review by jthanwer — APPROVED** [review]
Everything looks perfect. This is really good work. 
I cannot review all the files individually but I looked at the general structure and the dependencies (workflow) between the Config Class, the main function and the models default jobs and features. 

I really liked:
- The refactoring of run_chain.py (creation of the Config class and very small main function)
- The conversion of config.py to config.yml. It is much more structured like this.
- The "features" feature and more generally the models.yaml workflow. It is a solid basis for future implementation.

**Comment by mjaehn** [comment]
@jthanwer Thanks a lot for your review - it is much appreciated! I am glad you like the changes. I will wait with the merge until the afternoon so that @efmkoene or @gredvis can add something to that. If something comes up afterwards we will always be able to apply a hotfix or include it in a future version ([there are already plans for new features on the way](https://github.com/C2SM/processing-chain/issues?q=is%3Aissue+is%3Aopen+label%3Av3.1)).

**Pull request merged**
