### PR TITLE
use pathlib

### PR DESCRIPTION
**Pull request by leclairm**
See this PR as a draft that can be used elsewhere. Probably not merge in the end.

This is not tested. Maybe it clashes with other parts of the code.
Also probably many other places of the code could make use of pathlib.

### CODE REVIEW

**Comment by mjaehn** [comment]
What is the general motivation in using Pathlib?

**Comment by mjaehn** [comment]
I am fine with that and I agree that the readability is improved. It just needs testing and the package has  to be added to https://github.com/C2SM/processing-chain/blob/v3.1-rc/env/environment.yml and https://github.com/C2SM/processing-chain/blob/v3.1-rc/docs/requirements.txt

**Comment by leclairm** [comment]
> I am fine with that and I agree that the readability is improved. It just needs testing and the package has to be added to https://github.com/C2SM/processing-chain/blob/v3.1-rc/env/environment.yml and https://github.com/C2SM/processing-chain/blob/v3.1-rc/docs/requirements.txt

Well, its not a dependency, it's part of the standard python distribution.

**Comment by mjaehn** [comment]
Even better! 👍🏻

**Pull request closed without merging**
