### PR TITLE
Spack v0.18.1

### PR DESCRIPTION
**Pull request by mjaehn**
This PR introduces the new c2sm-spack infrastructure (v0.18.1) that is recommended to all users. Additionally, `int2lm`, `cosmo` and `icon` are compiled via `spack dev-build`s since this is similar to what users usually do (and thus should be tested). With that, no more hacky `spack location` commands within the config files are used to access the executables.

### CODE REVIEW

**Comment by mjaehn** [comment]
launch jenkins

**Comment by mjaehn** [comment]
launch jenkins

**Comment by mjaehn** [comment]
launch jenkins

**Comment by mjaehn** [comment]
launch jenkins

**Comment by mjaehn** [comment]
launch jenkins

**Comment by mjaehn** [comment]
launch jenkins

**Comment by mjaehn** [comment]
launch jenkins

**Comment by mjaehn** [comment]
launch jenkins

**Comment by mjaehn** [comment]
launch jenkins

**Comment by mjaehn** [comment]
@efmkoene This is now ready for review as all tests are green ✅

**Review by efmkoene — APPROVED** [review]
Looks good to me!

**Pull request merged**
